// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/chord-construction": {
    params: {};
  };
  "/chord-construction/basic-triads/level5": {
    params: {};
  };
  "/chord-construction/basic-triads/level6": {
    params: {};
  };
  "/chord-construction/basic-triads/level7": {
    params: {};
  };
  "/chord-construction/jazz-chords/level1": {
    params: {};
  };
  "/chord-construction/seventh-chords/level6": {
    params: {};
  };
  "/chord-construction/seventh-chords/level7": {
    params: {};
  };
  "/chord-construction/seventh-chords/level8": {
    params: {};
  };
  "/chord-recognition": {
    params: {};
  };
  "/chord-recognition/basic-triads": {
    params: {};
  };
  "/chord-recognition/basic-triads/recognition/level1": {
    params: {};
  };
  "/chord-recognition/basic-triads/recognition/level2": {
    params: {};
  };
  "/chord-recognition/basic-triads/recognition/level3": {
    params: {};
  };
  "/chord-recognition/basic-triads/recognition/level4": {
    params: {};
  };
  "/chord-recognition/chord-progressions": {
    params: {};
  };
  "/chord-recognition/chord-progressions/level1": {
    params: {};
  };
  "/chord-recognition/chord-progressions/level2": {
    params: {};
  };
  "/chord-recognition/chord-progressions/level3": {
    params: {};
  };
  "/chord-recognition/jazz-chords": {
    params: {};
  };
  "/chord-recognition/jazz-chords/recognition/level1": {
    params: {};
  };
  "/chord-recognition/jazz-chords/recognition/level2": {
    params: {};
  };
  "/chord-recognition/jazz-chords/recognition/level3": {
    params: {};
  };
  "/chord-recognition/jazz-chords/recognition/level4": {
    params: {};
  };
  "/chord-recognition/seventh-chords": {
    params: {};
  };
  "/chord-recognition/seventh-chords/recognition/level1": {
    params: {};
  };
  "/chord-recognition/seventh-chords/recognition/level2": {
    params: {};
  };
  "/chord-recognition/seventh-chords/recognition/level3": {
    params: {};
  };
  "/chord-recognition/seventh-chords/recognition/level4": {
    params: {};
  };
  "/chord-recognition/seventh-chords/recognition/level5": {
    params: {};
  };
  "/counterpoint": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/midi-training": {
    params: {};
  };
  "/unauthorized": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/register" | "/chord-construction" | "/chord-construction/basic-triads/level5" | "/chord-construction/basic-triads/level6" | "/chord-construction/basic-triads/level7" | "/chord-construction/jazz-chords/level1" | "/chord-construction/seventh-chords/level6" | "/chord-construction/seventh-chords/level7" | "/chord-construction/seventh-chords/level8" | "/chord-recognition" | "/chord-recognition/basic-triads" | "/chord-recognition/basic-triads/recognition/level1" | "/chord-recognition/basic-triads/recognition/level2" | "/chord-recognition/basic-triads/recognition/level3" | "/chord-recognition/basic-triads/recognition/level4" | "/chord-recognition/chord-progressions" | "/chord-recognition/chord-progressions/level1" | "/chord-recognition/chord-progressions/level2" | "/chord-recognition/chord-progressions/level3" | "/chord-recognition/jazz-chords" | "/chord-recognition/jazz-chords/recognition/level1" | "/chord-recognition/jazz-chords/recognition/level2" | "/chord-recognition/jazz-chords/recognition/level3" | "/chord-recognition/jazz-chords/recognition/level4" | "/chord-recognition/seventh-chords" | "/chord-recognition/seventh-chords/recognition/level1" | "/chord-recognition/seventh-chords/recognition/level2" | "/chord-recognition/seventh-chords/recognition/level3" | "/chord-recognition/seventh-chords/recognition/level4" | "/chord-recognition/seventh-chords/recognition/level5" | "/counterpoint" | "/dashboard" | "/midi-training" | "/unauthorized" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./auth/login/page.jsx": {
    id: "auth/login/page";
    page: "/auth/login";
  };
  "./auth/register/page.jsx": {
    id: "auth/register/page";
    page: "/auth/register";
  };
  "./chord-construction/page.jsx": {
    id: "chord-construction/page";
    page: "/chord-construction";
  };
  "./chord-construction/basic-triads/level5/page.jsx": {
    id: "chord-construction/basic-triads/level5/page";
    page: "/chord-construction/basic-triads/level5";
  };
  "./chord-construction/basic-triads/level6/page.jsx": {
    id: "chord-construction/basic-triads/level6/page";
    page: "/chord-construction/basic-triads/level6";
  };
  "./chord-construction/basic-triads/level7/page.jsx": {
    id: "chord-construction/basic-triads/level7/page";
    page: "/chord-construction/basic-triads/level7";
  };
  "./chord-construction/jazz-chords/level1/page.jsx": {
    id: "chord-construction/jazz-chords/level1/page";
    page: "/chord-construction/jazz-chords/level1";
  };
  "./chord-construction/seventh-chords/level6/page.jsx": {
    id: "chord-construction/seventh-chords/level6/page";
    page: "/chord-construction/seventh-chords/level6";
  };
  "./chord-construction/seventh-chords/level7/page.jsx": {
    id: "chord-construction/seventh-chords/level7/page";
    page: "/chord-construction/seventh-chords/level7";
  };
  "./chord-construction/seventh-chords/level8/page.jsx": {
    id: "chord-construction/seventh-chords/level8/page";
    page: "/chord-construction/seventh-chords/level8";
  };
  "./chord-recognition/page.jsx": {
    id: "chord-recognition/page";
    page: "/chord-recognition";
  };
  "./chord-recognition/basic-triads/page.jsx": {
    id: "chord-recognition/basic-triads/page";
    page: "/chord-recognition/basic-triads";
  };
  "./chord-recognition/basic-triads/recognition/level1/page.jsx": {
    id: "chord-recognition/basic-triads/recognition/level1/page";
    page: "/chord-recognition/basic-triads/recognition/level1";
  };
  "./chord-recognition/basic-triads/recognition/level2/page.jsx": {
    id: "chord-recognition/basic-triads/recognition/level2/page";
    page: "/chord-recognition/basic-triads/recognition/level2";
  };
  "./chord-recognition/basic-triads/recognition/level3/page.jsx": {
    id: "chord-recognition/basic-triads/recognition/level3/page";
    page: "/chord-recognition/basic-triads/recognition/level3";
  };
  "./chord-recognition/basic-triads/recognition/level4/page.jsx": {
    id: "chord-recognition/basic-triads/recognition/level4/page";
    page: "/chord-recognition/basic-triads/recognition/level4";
  };
  "./chord-recognition/chord-progressions/page.jsx": {
    id: "chord-recognition/chord-progressions/page";
    page: "/chord-recognition/chord-progressions";
  };
  "./chord-recognition/chord-progressions/level1/page.jsx": {
    id: "chord-recognition/chord-progressions/level1/page";
    page: "/chord-recognition/chord-progressions/level1";
  };
  "./chord-recognition/chord-progressions/level2/page.jsx": {
    id: "chord-recognition/chord-progressions/level2/page";
    page: "/chord-recognition/chord-progressions/level2";
  };
  "./chord-recognition/chord-progressions/level3/page.jsx": {
    id: "chord-recognition/chord-progressions/level3/page";
    page: "/chord-recognition/chord-progressions/level3";
  };
  "./chord-recognition/jazz-chords/page.jsx": {
    id: "chord-recognition/jazz-chords/page";
    page: "/chord-recognition/jazz-chords";
  };
  "./chord-recognition/jazz-chords/recognition/level1/page.jsx": {
    id: "chord-recognition/jazz-chords/recognition/level1/page";
    page: "/chord-recognition/jazz-chords/recognition/level1";
  };
  "./chord-recognition/jazz-chords/recognition/level2/page.jsx": {
    id: "chord-recognition/jazz-chords/recognition/level2/page";
    page: "/chord-recognition/jazz-chords/recognition/level2";
  };
  "./chord-recognition/jazz-chords/recognition/level3/page.jsx": {
    id: "chord-recognition/jazz-chords/recognition/level3/page";
    page: "/chord-recognition/jazz-chords/recognition/level3";
  };
  "./chord-recognition/jazz-chords/recognition/level4/page.jsx": {
    id: "chord-recognition/jazz-chords/recognition/level4/page";
    page: "/chord-recognition/jazz-chords/recognition/level4";
  };
  "./chord-recognition/seventh-chords/page.jsx": {
    id: "chord-recognition/seventh-chords/page";
    page: "/chord-recognition/seventh-chords";
  };
  "./chord-recognition/seventh-chords/recognition/level1/page.jsx": {
    id: "chord-recognition/seventh-chords/recognition/level1/page";
    page: "/chord-recognition/seventh-chords/recognition/level1";
  };
  "./chord-recognition/seventh-chords/recognition/level2/page.jsx": {
    id: "chord-recognition/seventh-chords/recognition/level2/page";
    page: "/chord-recognition/seventh-chords/recognition/level2";
  };
  "./chord-recognition/seventh-chords/recognition/level3/page.jsx": {
    id: "chord-recognition/seventh-chords/recognition/level3/page";
    page: "/chord-recognition/seventh-chords/recognition/level3";
  };
  "./chord-recognition/seventh-chords/recognition/level4/page.jsx": {
    id: "chord-recognition/seventh-chords/recognition/level4/page";
    page: "/chord-recognition/seventh-chords/recognition/level4";
  };
  "./chord-recognition/seventh-chords/recognition/level5/page.jsx": {
    id: "chord-recognition/seventh-chords/recognition/level5/page";
    page: "/chord-recognition/seventh-chords/recognition/level5";
  };
  "./counterpoint/page.jsx": {
    id: "counterpoint/page";
    page: "/counterpoint";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./midi-training/page.jsx": {
    id: "midi-training/page";
    page: "/midi-training";
  };
  "./unauthorized/page.jsx": {
    id: "unauthorized/page";
    page: "/unauthorized";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};