// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/core-training/chord-construction": {
    params: {};
  };
  "/core-training/chord-construction/:category/:level": {
    params: {
      "category": string;
      "level": string;
    };
  };
  "/core-training/chord-progressions": {
    params: {};
  };
  "/core-training/chord-progressions/:level": {
    params: {
      "level": string;
    };
  };
  "/core-training/chord-recognition": {
    params: {};
  };
  "/core-training/chord-recognition/:category/:level": {
    params: {
      "category": string;
      "level": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/ear-training/chord-progression-transcription": {
    params: {};
  };
  "/ear-training/chord-progression-transcription/:level": {
    params: {
      "level": string;
    };
  };
  "/ear-training/transcription": {
    params: {};
  };
  "/ear-training/transcription/:category/:level": {
    params: {
      "category": string;
      "level": string;
    };
  };
  "/leaderboard": {
    params: {};
  };
  "/practice/counterpoint": {
    params: {};
  };
  "/practice/counterpoint/:species/:voices/:level": {
    params: {
      "species": string;
      "voices": string;
      "level": string;
    };
  };
  "/practice/counterpoint/:species/:voices/:level/practice": {
    params: {
      "species": string;
      "voices": string;
      "level": string;
    };
  };
  "/store": {
    params: {};
  };
  "/unauthorized": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/auth/login" | "/auth/register" | "/blog" | "/blog/:slug" | "/contact" | "/core-training/chord-construction" | "/core-training/chord-construction/:category/:level" | "/core-training/chord-progressions" | "/core-training/chord-progressions/:level" | "/core-training/chord-recognition" | "/core-training/chord-recognition/:category/:level" | "/dashboard" | "/ear-training/chord-progression-transcription" | "/ear-training/chord-progression-transcription/:level" | "/ear-training/transcription" | "/ear-training/transcription/:category/:level" | "/leaderboard" | "/practice/counterpoint" | "/practice/counterpoint/:species/:voices/:level" | "/practice/counterpoint/:species/:voices/:level/practice" | "/store" | "/unauthorized" | "/*";
  };
  "./page.tsx": {
    id: "page";
    page: "/";
  };
  "./about/page.tsx": {
    id: "about/page";
    page: "/about";
  };
  "./auth/login/page.tsx": {
    id: "auth/login/page";
    page: "/auth/login";
  };
  "./auth/register/page.tsx": {
    id: "auth/register/page";
    page: "/auth/register";
  };
  "./blog/page.tsx": {
    id: "blog/page";
    page: "/blog";
  };
  "./blog/[slug]/page.tsx": {
    id: "blog/[slug]/page";
    page: "/blog/:slug";
  };
  "./contact/page.tsx": {
    id: "contact/page";
    page: "/contact";
  };
  "./core-training/chord-construction/page.tsx": {
    id: "core-training/chord-construction/page";
    page: "/core-training/chord-construction";
  };
  "./core-training/chord-construction/[category]/[level]/page.tsx": {
    id: "core-training/chord-construction/[category]/[level]/page";
    page: "/core-training/chord-construction/:category/:level";
  };
  "./core-training/chord-progressions/page.tsx": {
    id: "core-training/chord-progressions/page";
    page: "/core-training/chord-progressions";
  };
  "./core-training/chord-progressions/[level]/page.tsx": {
    id: "core-training/chord-progressions/[level]/page";
    page: "/core-training/chord-progressions/:level";
  };
  "./core-training/chord-recognition/page.tsx": {
    id: "core-training/chord-recognition/page";
    page: "/core-training/chord-recognition";
  };
  "./core-training/chord-recognition/[category]/[level]/page.tsx": {
    id: "core-training/chord-recognition/[category]/[level]/page";
    page: "/core-training/chord-recognition/:category/:level";
  };
  "./dashboard/page.tsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./ear-training/chord-progression-transcription/page.tsx": {
    id: "ear-training/chord-progression-transcription/page";
    page: "/ear-training/chord-progression-transcription";
  };
  "./ear-training/chord-progression-transcription/[level]/page.tsx": {
    id: "ear-training/chord-progression-transcription/[level]/page";
    page: "/ear-training/chord-progression-transcription/:level";
  };
  "./ear-training/transcription/page.tsx": {
    id: "ear-training/transcription/page";
    page: "/ear-training/transcription";
  };
  "./ear-training/transcription/[category]/[level]/page.tsx": {
    id: "ear-training/transcription/[category]/[level]/page";
    page: "/ear-training/transcription/:category/:level";
  };
  "./leaderboard/page.tsx": {
    id: "leaderboard/page";
    page: "/leaderboard";
  };
  "./practice/counterpoint/page.tsx": {
    id: "practice/counterpoint/page";
    page: "/practice/counterpoint";
  };
  "./practice/counterpoint/[species]/[voices]/[level]/page.tsx": {
    id: "practice/counterpoint/[species]/[voices]/[level]/page";
    page: "/practice/counterpoint/:species/:voices/:level";
  };
  "./practice/counterpoint/[species]/[voices]/[level]/practice/page.tsx": {
    id: "practice/counterpoint/[species]/[voices]/[level]/practice/page";
    page: "/practice/counterpoint/:species/:voices/:level/practice";
  };
  "./store/page.tsx": {
    id: "store/page";
    page: "/store";
  };
  "./unauthorized/page.tsx": {
    id: "unauthorized/page";
    page: "/unauthorized";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};