// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chord-recognition": {
    params: {};
  };
  "/chord-recognition/basic-triads": {
    params: {};
  };
  "/chord-recognition/basic-triads/construction/level5": {
    params: {};
  };
  "/chord-recognition/basic-triads/construction/level6": {
    params: {};
  };
  "/chord-recognition/basic-triads/construction/level7": {
    params: {};
  };
  "/chord-recognition/basic-triads/recognition/level1": {
    params: {};
  };
  "/chord-recognition/basic-triads/recognition/level2": {
    params: {};
  };
  "/chord-recognition/basic-triads/recognition/level3": {
    params: {};
  };
  "/chord-recognition/basic-triads/recognition/level4": {
    params: {};
  };
  "/chord-recognition/chord-progressions": {
    params: {};
  };
  "/chord-recognition/chord-progressions/level1": {
    params: {};
  };
  "/chord-recognition/chord-progressions/level2": {
    params: {};
  };
  "/chord-recognition/chord-progressions/level3": {
    params: {};
  };
  "/chord-recognition/extended-chords": {
    params: {};
  };
  "/chord-recognition/extended-chords/construction/level6": {
    params: {};
  };
  "/chord-recognition/extended-chords/construction/level7": {
    params: {};
  };
  "/chord-recognition/extended-chords/construction/level8": {
    params: {};
  };
  "/chord-recognition/extended-chords/recognition/level1": {
    params: {};
  };
  "/chord-recognition/extended-chords/recognition/level2": {
    params: {};
  };
  "/chord-recognition/extended-chords/recognition/level3": {
    params: {};
  };
  "/chord-recognition/extended-chords/recognition/level4": {
    params: {};
  };
  "/chord-recognition/extended-chords/recognition/level5": {
    params: {};
  };
  "/chord-recognition/jazz-chords": {
    params: {};
  };
  "/counterpoint": {
    params: {};
  };
  "/midi-training": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chord-recognition" | "/chord-recognition/basic-triads" | "/chord-recognition/basic-triads/construction/level5" | "/chord-recognition/basic-triads/construction/level6" | "/chord-recognition/basic-triads/construction/level7" | "/chord-recognition/basic-triads/recognition/level1" | "/chord-recognition/basic-triads/recognition/level2" | "/chord-recognition/basic-triads/recognition/level3" | "/chord-recognition/basic-triads/recognition/level4" | "/chord-recognition/chord-progressions" | "/chord-recognition/chord-progressions/level1" | "/chord-recognition/chord-progressions/level2" | "/chord-recognition/chord-progressions/level3" | "/chord-recognition/extended-chords" | "/chord-recognition/extended-chords/construction/level6" | "/chord-recognition/extended-chords/construction/level7" | "/chord-recognition/extended-chords/construction/level8" | "/chord-recognition/extended-chords/recognition/level1" | "/chord-recognition/extended-chords/recognition/level2" | "/chord-recognition/extended-chords/recognition/level3" | "/chord-recognition/extended-chords/recognition/level4" | "/chord-recognition/extended-chords/recognition/level5" | "/chord-recognition/jazz-chords" | "/counterpoint" | "/midi-training" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./chord-recognition/page.jsx": {
    id: "chord-recognition/page";
    page: "/chord-recognition";
  };
  "./chord-recognition/basic-triads/page.jsx": {
    id: "chord-recognition/basic-triads/page";
    page: "/chord-recognition/basic-triads";
  };
  "./chord-recognition/basic-triads/construction/level5/page.jsx": {
    id: "chord-recognition/basic-triads/construction/level5/page";
    page: "/chord-recognition/basic-triads/construction/level5";
  };
  "./chord-recognition/basic-triads/construction/level6/page.jsx": {
    id: "chord-recognition/basic-triads/construction/level6/page";
    page: "/chord-recognition/basic-triads/construction/level6";
  };
  "./chord-recognition/basic-triads/construction/level7/page.jsx": {
    id: "chord-recognition/basic-triads/construction/level7/page";
    page: "/chord-recognition/basic-triads/construction/level7";
  };
  "./chord-recognition/basic-triads/recognition/level1/page.jsx": {
    id: "chord-recognition/basic-triads/recognition/level1/page";
    page: "/chord-recognition/basic-triads/recognition/level1";
  };
  "./chord-recognition/basic-triads/recognition/level2/page.jsx": {
    id: "chord-recognition/basic-triads/recognition/level2/page";
    page: "/chord-recognition/basic-triads/recognition/level2";
  };
  "./chord-recognition/basic-triads/recognition/level3/page.jsx": {
    id: "chord-recognition/basic-triads/recognition/level3/page";
    page: "/chord-recognition/basic-triads/recognition/level3";
  };
  "./chord-recognition/basic-triads/recognition/level4/page.jsx": {
    id: "chord-recognition/basic-triads/recognition/level4/page";
    page: "/chord-recognition/basic-triads/recognition/level4";
  };
  "./chord-recognition/chord-progressions/page.jsx": {
    id: "chord-recognition/chord-progressions/page";
    page: "/chord-recognition/chord-progressions";
  };
  "./chord-recognition/chord-progressions/level1/page.jsx": {
    id: "chord-recognition/chord-progressions/level1/page";
    page: "/chord-recognition/chord-progressions/level1";
  };
  "./chord-recognition/chord-progressions/level2/page.jsx": {
    id: "chord-recognition/chord-progressions/level2/page";
    page: "/chord-recognition/chord-progressions/level2";
  };
  "./chord-recognition/chord-progressions/level3/page.jsx": {
    id: "chord-recognition/chord-progressions/level3/page";
    page: "/chord-recognition/chord-progressions/level3";
  };
  "./chord-recognition/extended-chords/page.jsx": {
    id: "chord-recognition/extended-chords/page";
    page: "/chord-recognition/extended-chords";
  };
  "./chord-recognition/extended-chords/construction/level6/page.jsx": {
    id: "chord-recognition/extended-chords/construction/level6/page";
    page: "/chord-recognition/extended-chords/construction/level6";
  };
  "./chord-recognition/extended-chords/construction/level7/page.jsx": {
    id: "chord-recognition/extended-chords/construction/level7/page";
    page: "/chord-recognition/extended-chords/construction/level7";
  };
  "./chord-recognition/extended-chords/construction/level8/page.jsx": {
    id: "chord-recognition/extended-chords/construction/level8/page";
    page: "/chord-recognition/extended-chords/construction/level8";
  };
  "./chord-recognition/extended-chords/recognition/level1/page.jsx": {
    id: "chord-recognition/extended-chords/recognition/level1/page";
    page: "/chord-recognition/extended-chords/recognition/level1";
  };
  "./chord-recognition/extended-chords/recognition/level2/page.jsx": {
    id: "chord-recognition/extended-chords/recognition/level2/page";
    page: "/chord-recognition/extended-chords/recognition/level2";
  };
  "./chord-recognition/extended-chords/recognition/level3/page.jsx": {
    id: "chord-recognition/extended-chords/recognition/level3/page";
    page: "/chord-recognition/extended-chords/recognition/level3";
  };
  "./chord-recognition/extended-chords/recognition/level4/page.jsx": {
    id: "chord-recognition/extended-chords/recognition/level4/page";
    page: "/chord-recognition/extended-chords/recognition/level4";
  };
  "./chord-recognition/extended-chords/recognition/level5/page.jsx": {
    id: "chord-recognition/extended-chords/recognition/level5/page";
    page: "/chord-recognition/extended-chords/recognition/level5";
  };
  "./chord-recognition/jazz-chords/page.jsx": {
    id: "chord-recognition/jazz-chords/page";
    page: "/chord-recognition/jazz-chords";
  };
  "./counterpoint/page.jsx": {
    id: "counterpoint/page";
    page: "/counterpoint";
  };
  "./midi-training/page.jsx": {
    id: "midi-training/page";
    page: "/midi-training";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};